[tool.poetry]
name = "haikuincidence"
version = "0.1.0"
description = "Find tweets that contain coincidental haikus and tweet these beautiful poems"
authors = ["Matt Mollison <matt.mollison@gmail.com>"]

[tool.poetry.dependencies]
ftfy = "^5.9"
inflect = "^5.0"
nltk = "^3.5"
psycopg2-binary = "^2.8"
python-dotenv = "^0.15"
pytz = "^2021"
python = "^3.9"
sqlalchemy = "^1.3"
twython = "^3.8"
unidecode = "^1.2"

[tool.poetry.dev-dependencies]
black = "20.8b1"
flake8 = "^3.9"
isort = "^5.8"
# mypy = "^0.812"
# pytest = "^6.2"

[tool.isort]
profile = "black"
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88
