[build-system]
requires = ["poetry>=1.1"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "haikuincidence"
version = "0.1.0"
description = "Find tweets that contain coincidental haikus and tweet these beautiful poems"
authors = ["Matt Mollison <matt.mollison@gmail.com>"]

[tool.poetry.dependencies]
ftfy = "~6.1.1"
inflect = "~5.4.0"
nltk = "~3.7.0"
psycopg2-binary = "~2.9.3"
python-dotenv = "~0.19.2"
pytz = "~2021.3"
python = ">=3.9,<3.10"
sqlalchemy = "~1.4.31"
twython = "~3.9.1"
unidecode = "~1.3.3"

[tool.poetry.dev-dependencies]
black = "~22.1.0"
flake8 = "~4.0.1"
isort = "~5.10.1"
mypy = "~0.931"
pytest = "~7.0.1"

[tool.black]
line-length = 88

[tool.isort]
profile = "black"
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88
