[build-system]
requires = ["poetry>=1.1"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "haikuincidence"
version = "0.1.0"
description = "Find tweets that contain coincidental haikus and tweet these beautiful poems"
authors = ["Matt Mollison <matt.mollison@gmail.com>"]

[tool.poetry.dependencies]
ftfy = "~6.0.3"
inflect = "~5.3.0"
nltk = "~3.6.5"
psycopg2-binary = "~2.9.1"
python-dotenv = "~0.19.2"
pytz = "~2021.3"
python = ">=3.9,<3.10"
sqlalchemy = "~1.4.27"
twython = "~3.9.1"
unidecode = "~1.3.2"

[tool.poetry.dev-dependencies]
black = "21.11b1"
flake8 = "~4.0.1"
isort = "~5.10.1"
mypy = "~0.910"
pytest = "~6.2.5"

[tool.black]
line-length = 100

[tool.isort]
profile = "black"
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88
