name: Code Quality

on:
  pull_request:
    branches:
      - main

env:
  PYTHON_VERSION: 3.9

jobs:
  lint:
    name: Lint and Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            python -m pip install -r requirements-dev.txt

      - name: Check formatting
        run: black --check .

      - name: Check imports
        run: isort --check .

      - name: Check code style
        run: flake8 .
