name: Build and deploy

on:
  push:

jobs:
  build:
    name: Build and deploy to Heroku
    runs-on: ubuntu-latest
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      HEROKU_PROCESS_TYPE: worker

    if: ${{ env.GITHUB_REF_NAME }} == 'main' || contains(github.event.head_commit.message, '#deploy')
    steps:
      - name: Print branch name
        run: echo ${{ env.GITHUB_REF_NAME }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Log in to Heroku Container registry
        run: docker login --username=_ --password=${HEROKU_API_KEY} registry.heroku.com

      # Build and deploy app
      - name: Build
        run: docker build -t registry.heroku.com/${HEROKU_APP_NAME}/${HEROKU_PROCESS_TYPE} .

      - name: Push
        run: docker push registry.heroku.com/${HEROKU_APP_NAME}/${HEROKU_PROCESS_TYPE}:latest

      - name: Release
        run: heroku container:release -a ${HEROKU_APP_NAME} ${HEROKU_PROCESS_TYPE}
